// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Xbim.Ifc4x3.SharedBldgElements
{
	public enum IfcBuildingSystemTypeEnum : byte
	{
		@FENESTRATION ,
		@FOUNDATION ,
		@LOADBEARING ,
		@OUTERSHELL ,
		@SHADING ,
		@TRANSPORT ,
		@REINFORCING ,
		@PRESTRESSING ,
		@EROSIONPREVENTION ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}