#region XbimHeader

// The eXtensible Building Information Modelling (xBIM) Toolkit
// Solution:    XbimComplete
// Project:     Xbim.Ifc
// Filename:    IfcDerivedUnitEnum.cs
// Published:   01, 2012
// Last Edited: 9:04 AM on 20 12 2011
// (See accompanying copyright.rtf)

#endregion

namespace Xbim.Ifc2x3.MeasureResource
{
    /// <summary>
    ///   An enumeration type for allowed types of derived units.
    /// </summary>
    public enum IfcDerivedUnitEnum
    {
        ANGULARVELOCITYUNIT,
        COMPOUNDPLANEANGLEUNIT,
        DYNAMICVISCOSITYUNIT,
        HEATFLUXDENSITYUNIT,
        INTEGERCOUNTRATEUNIT,
        ISOTHERMALMOISTURECAPACITYUNIT,
        KINEMATICVISCOSITYUNIT,
        LINEARVELOCITYUNIT,
        MASSDENSITYUNIT,
        MASSFLOWRATEUNIT,
        MOISTUREDIFFUSIVITYUNIT,
        MOLECULARWEIGHTUNIT,
        SPECIFICHEATCAPACITYUNIT,
        THERMALADMITTANCEUNIT,
        THERMALCONDUCTANCEUNIT,
        THERMALRESISTANCEUNIT,
        THERMALTRANSMITTANCEUNIT,
        VAPORPERMEABILITYUNIT,
        VOLUMETRICFLOWRATEUNIT,
        ROTATIONALFREQUENCYUNIT,
        TORQUEUNIT,
        MOMENTOFINERTIAUNIT,
        LINEARMOMENTUNIT,
        LINEARFORCEUNIT,
        PLANARFORCEUNIT,
        MODULUSOFELASTICITYUNIT,
        SHEARMODULUSUNIT,
        LINEARSTIFFNESSUNIT,
        ROTATIONALSTIFFNESSUNIT,
        MODULUSOFSUBGRADEREACTIONUNIT,
        ACCELERATIONUNIT,
        CURVATUREUNIT,
        HEATINGVALUEUNIT,
        IONCONCENTRATIONUNIT,
        LUMINOUSINTENSITYDISTRIBUTIONUNIT,
        MASSPERLENGTHUNIT,
        MODULUSOFLINEARSUBGRADEREACTIONUNIT,
        MODULUSOFROTATIONALSUBGRADEREACTIONUNIT,
        PHUNIT,
        ROTATIONALMASSUNIT,
        SECTIONAREAINTEGRALUNIT,
        SECTIONMODULUSUNIT,
        SOUNDPOWERUNIT,
        SOUNDPRESSUREUNIT,
        TEMPERATUREGRADIENTUNIT,
        THERMALEXPANSIONCOEFFICIENTUNIT,
        WARPINGCONSTANTUNIT,
        WARPINGMOMENTUNIT,
        USERDEFINED
    }
}