// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Xbim.Ifc4x3.ElectricalDomain
{
	public enum IfcSwitchingDeviceTypeEnum : byte
	{
		@CONTACTOR ,
		@DIMMERSWITCH ,
		@EMERGENCYSTOP ,
		@KEYPAD ,
		@MOMENTARYSWITCH ,
		@SELECTORSWITCH ,
		@STARTER ,
		@SWITCHDISCONNECTOR ,
		@TOGGLESWITCH ,
		@RELAY ,
		@START_AND_STOP_EQUIPMENT ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}