// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Xbim.Ifc4.Interfaces
{
	public enum IfcRecurrenceTypeEnum : byte
	{
		@DAILY ,
		@WEEKLY ,
		@MONTHLY_BY_DAY_OF_MONTH ,
		@MONTHLY_BY_POSITION ,
		@BY_DAY_COUNT ,
		@BY_WEEKDAY_COUNT ,
		@YEARLY_BY_DAY_OF_MONTH ,
		@YEARLY_BY_POSITION 
	}
}