// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Xbim.Ifc4.Interfaces
{
	public enum IfcStairTypeEnum : byte
	{
		@STRAIGHT_RUN_STAIR ,
		@TWO_STRAIGHT_RUN_STAIR ,
		@QUARTER_WINDING_STAIR ,
		@QUARTER_TURN_STAIR ,
		@HALF_WINDING_STAIR ,
		@HALF_TURN_STAIR ,
		@TWO_QUARTER_WINDING_STAIR ,
		@TWO_QUARTER_TURN_STAIR ,
		@THREE_QUARTER_WINDING_STAIR ,
		@THREE_QUARTER_TURN_STAIR ,
		@SPIRAL_STAIR ,
		@DOUBLE_RETURN_STAIR ,
		@CURVED_RUN_STAIR ,
		@TWO_CURVED_RUN_STAIR ,
		@USERDEFINED ,
		@NOTDEFINED 
	}
}