// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;

// ReSharper disable once CheckNamespace
namespace Xbim.Ifc2x3.HVACDomain
{
	public partial class @IfcAirTerminalBoxType : IIfcAirTerminalBoxType
	{
		Ifc4.HvacDomain.IfcAirTerminalBoxTypeEnum IIfcAirTerminalBoxType.PredefinedType 
		{ 
			get
			{
				switch (PredefinedType)
				{
					case IfcAirTerminalBoxTypeEnum.CONSTANTFLOW:
						return Ifc4.HvacDomain.IfcAirTerminalBoxTypeEnum.CONSTANTFLOW;
					
					case IfcAirTerminalBoxTypeEnum.VARIABLEFLOWPRESSUREDEPENDANT:
						return Ifc4.HvacDomain.IfcAirTerminalBoxTypeEnum.VARIABLEFLOWPRESSUREDEPENDANT;
					
					case IfcAirTerminalBoxTypeEnum.VARIABLEFLOWPRESSUREINDEPENDANT:
						return Ifc4.HvacDomain.IfcAirTerminalBoxTypeEnum.VARIABLEFLOWPRESSUREINDEPENDANT;
					
					case IfcAirTerminalBoxTypeEnum.USERDEFINED:
						return Ifc4.HvacDomain.IfcAirTerminalBoxTypeEnum.USERDEFINED;
					
					case IfcAirTerminalBoxTypeEnum.NOTDEFINED:
						return Ifc4.HvacDomain.IfcAirTerminalBoxTypeEnum.NOTDEFINED;
					
					
					default:
						throw new System.ArgumentOutOfRangeException();
				}
			} 
		}
	}
}