// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Interfaces;
using System.Collections.Generic;

// ReSharper disable once CheckNamespace
namespace Xbim.Ifc2x3.GeometryResource
{
	public partial class @IfcCartesianTransformationOperator3DnonUniform : IIfcCartesianTransformationOperator3DnonUniform
	{
		double? IIfcCartesianTransformationOperator3DnonUniform.Scale2 
		{ 
			get
			{
				throw new System.NotImplementedException();
			} 
		}
		double? IIfcCartesianTransformationOperator3DnonUniform.Scale3 
		{ 
			get
			{
				throw new System.NotImplementedException();
			} 
		}
	}
}