// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;

// ReSharper disable once CheckNamespace
namespace Xbim.Ifc2x3.PresentationDimensioningResource
{
	public partial class @IfcDimensionCurveTerminator : IIfcStyledItem
	{
		IIfcRepresentationItem IIfcStyledItem.Item 
		{ 
			get
			{
				//TODO: Handle return of Item for which no match was found
				throw new System.NotImplementedException();
			} 
		}
		IEnumerable<Xbim.Ifc4.PresentationAppearanceResource.IfcStyleAssignmentSelect> IIfcStyledItem.Styles 
		{ 
			get
			{
				//TODO: Handle return of Styles for which no match was found
				throw new System.NotImplementedException();
			} 
		}
		Xbim.Ifc4.MeasureResource.IfcLabel? IIfcStyledItem.Name 
		{ 
			get
			{
				//TODO: Handle return of Name for which no match was found
				throw new System.NotImplementedException();
			} 
		}
	}
}