// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;

// ReSharper disable once CheckNamespace
namespace Xbim.Ifc2x3.ExternalReferenceResource
{
	public partial class @IfcExternalReference : IIfcExternalReference
	{
		Ifc4.ExternalReferenceResource.IfcURIReference? IIfcExternalReference.Location 
		{ 
			get
			{
				if (Location == null) return null;
				return new Ifc4.ExternalReferenceResource.IfcURIReference((string)Location);
			} 
		}
		Ifc4.MeasureResource.IfcIdentifier? IIfcExternalReference.Identification 
		{ 
			get
			{
				if (ItemReference == null) return null;
				return new Ifc4.MeasureResource.IfcIdentifier((string)ItemReference);
			} 
		}
		Ifc4.MeasureResource.IfcLabel? IIfcExternalReference.Name 
		{ 
			get
			{
				if (Name == null) return null;
				return new Ifc4.MeasureResource.IfcLabel((string)Name);
			} 
		}
		IEnumerable<IIfcExternalReferenceRelationship> IIfcExternalReference.ExternalReferenceForResources 
		{ 
			get
			{
				return Model.Instances.Where<IIfcExternalReferenceRelationship>(e => (e.RelatingReference as IfcExternalReference) == this);
			} 
		}
	}
}