// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;

// ReSharper disable once CheckNamespace
namespace Xbim.Ifc2x3.ElectricalDomain
{
	public partial class @IfcElectricMotorType : IIfcElectricMotorType
	{
		Xbim.Ifc4.ElectricalDomain.IfcElectricMotorTypeEnum IIfcElectricMotorType.PredefinedType 
		{ 
			get
			{
				switch (PredefinedType)
				{
					case Xbim.Ifc2x3.ElectricalDomain.IfcElectricMotorTypeEnum.DC:
						return Xbim.Ifc4.ElectricalDomain.IfcElectricMotorTypeEnum.DC;
					
					case Xbim.Ifc2x3.ElectricalDomain.IfcElectricMotorTypeEnum.INDUCTION:
						return Xbim.Ifc4.ElectricalDomain.IfcElectricMotorTypeEnum.INDUCTION;
					
					case Xbim.Ifc2x3.ElectricalDomain.IfcElectricMotorTypeEnum.POLYPHASE:
						return Xbim.Ifc4.ElectricalDomain.IfcElectricMotorTypeEnum.POLYPHASE;
					
					case Xbim.Ifc2x3.ElectricalDomain.IfcElectricMotorTypeEnum.RELUCTANCESYNCHRONOUS:
						return Xbim.Ifc4.ElectricalDomain.IfcElectricMotorTypeEnum.RELUCTANCESYNCHRONOUS;
					
					case Xbim.Ifc2x3.ElectricalDomain.IfcElectricMotorTypeEnum.SYNCHRONOUS:
						return Xbim.Ifc4.ElectricalDomain.IfcElectricMotorTypeEnum.SYNCHRONOUS;
					
					case Xbim.Ifc2x3.ElectricalDomain.IfcElectricMotorTypeEnum.USERDEFINED:
						return Xbim.Ifc4.ElectricalDomain.IfcElectricMotorTypeEnum.USERDEFINED;
					
					case Xbim.Ifc2x3.ElectricalDomain.IfcElectricMotorTypeEnum.NOTDEFINED:
						return Xbim.Ifc4.ElectricalDomain.IfcElectricMotorTypeEnum.NOTDEFINED;
					
					
					default:
						throw new System.ArgumentOutOfRangeException();
				}
			} 
		}
	}
}