// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Interfaces;
using System.Collections.Generic;

// ReSharper disable once CheckNamespace
namespace Xbim.Ifc2x3.GeometricConstraintResource
{
	public partial class @IfcObjectPlacement : IIfcObjectPlacement
	{
		IEnumerable<IIfcProduct> IIfcObjectPlacement.PlacesObject 
		{ 
			get
			{
				throw new System.NotImplementedException();
			} 
		}
		IEnumerable<IIfcLocalPlacement> IIfcObjectPlacement.ReferencedByPlacements 
		{ 
			get
			{
				throw new System.NotImplementedException();
			} 
		}
	}
}