// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;

// ReSharper disable once CheckNamespace
namespace Xbim.Ifc2x3.ElectricalDomain
{
	public partial class @IfcProtectiveDeviceType : IIfcProtectiveDeviceType
	{
		Xbim.Ifc4.ElectricalDomain.IfcProtectiveDeviceTypeEnum IIfcProtectiveDeviceType.PredefinedType 
		{ 
			get
			{
				switch (PredefinedType)
				{
					case Xbim.Ifc2x3.ElectricalDomain.IfcProtectiveDeviceTypeEnum.FUSEDISCONNECTOR:
						return Xbim.Ifc4.ElectricalDomain.IfcProtectiveDeviceTypeEnum.FUSEDISCONNECTOR;
					
					case Xbim.Ifc2x3.ElectricalDomain.IfcProtectiveDeviceTypeEnum.CIRCUITBREAKER:
						return Xbim.Ifc4.ElectricalDomain.IfcProtectiveDeviceTypeEnum.CIRCUITBREAKER;
					
					case Xbim.Ifc2x3.ElectricalDomain.IfcProtectiveDeviceTypeEnum.EARTHFAILUREDEVICE:
						//## Handle translation of EARTHFAILUREDEVICE member from IfcProtectiveDeviceTypeEnum in property PredefinedType
						//TODO: Handle translation of EARTHFAILUREDEVICE member from IfcProtectiveDeviceTypeEnum in property PredefinedType
						throw new System.NotImplementedException();
						//##
										
					case Xbim.Ifc2x3.ElectricalDomain.IfcProtectiveDeviceTypeEnum.RESIDUALCURRENTCIRCUITBREAKER:
						return Xbim.Ifc4.ElectricalDomain.IfcProtectiveDeviceTypeEnum.RESIDUALCURRENTCIRCUITBREAKER;
					
					case Xbim.Ifc2x3.ElectricalDomain.IfcProtectiveDeviceTypeEnum.RESIDUALCURRENTSWITCH:
						return Xbim.Ifc4.ElectricalDomain.IfcProtectiveDeviceTypeEnum.RESIDUALCURRENTSWITCH;
					
					case Xbim.Ifc2x3.ElectricalDomain.IfcProtectiveDeviceTypeEnum.VARISTOR:
						return Xbim.Ifc4.ElectricalDomain.IfcProtectiveDeviceTypeEnum.VARISTOR;
					
					case Xbim.Ifc2x3.ElectricalDomain.IfcProtectiveDeviceTypeEnum.USERDEFINED:
						return Xbim.Ifc4.ElectricalDomain.IfcProtectiveDeviceTypeEnum.USERDEFINED;
					
					case Xbim.Ifc2x3.ElectricalDomain.IfcProtectiveDeviceTypeEnum.NOTDEFINED:
						return Xbim.Ifc4.ElectricalDomain.IfcProtectiveDeviceTypeEnum.NOTDEFINED;
					
					
					default:
						throw new System.ArgumentOutOfRangeException();
				}
			} 
		}
	}
}