// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Xbim.Common;

// ReSharper disable once CheckNamespace
namespace Xbim.Ifc2x3.ProductExtension
{
	public partial class @IfcRelVoidsElement : IIfcRelVoidsElement
	{

		[CrossSchemaAttribute(typeof(IIfcRelVoidsElement), 5)]
		IIfcElement IIfcRelVoidsElement.RelatingBuildingElement 
		{ 
			get
			{
				return RelatingBuildingElement;
			} 
			set
			{
				RelatingBuildingElement = value as IfcElement;
				
			}
		}

		[CrossSchemaAttribute(typeof(IIfcRelVoidsElement), 6)]
		IIfcFeatureElementSubtraction IIfcRelVoidsElement.RelatedOpeningElement 
		{ 
			get
			{
				return RelatedOpeningElement;
			} 
			set
			{
				RelatedOpeningElement = value as IfcFeatureElementSubtraction;
				
			}
		}
	//## Custom code
	//##
	}
}