// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Interfaces;
using System.Collections.Generic;

// ReSharper disable once CheckNamespace
namespace Xbim.Ifc2x3.ProductExtension
{
	public partial class @IfcRelAssociatesMaterial : IIfcRelAssociatesMaterial
	{
		Xbim.Ifc4.MaterialResource.IfcMaterialSelect IIfcRelAssociatesMaterial.RelatingMaterial 
		{ 
			get
			{
				throw new System.NotImplementedException();
			} 
		}
	}
}