// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;

// ReSharper disable once CheckNamespace
namespace Xbim.Ifc2x3.StructuralElementsDomain
{
	public partial class @IfcTendon : IIfcTendon
	{
		Ifc4.StructuralElementsDomain.IfcTendonTypeEnum? IIfcTendon.PredefinedType 
		{ 
			get
			{
				switch (PredefinedType)
				{
					case IfcTendonTypeEnum.STRAND:
						return Ifc4.StructuralElementsDomain.IfcTendonTypeEnum.STRAND;
					
					case IfcTendonTypeEnum.WIRE:
						return Ifc4.StructuralElementsDomain.IfcTendonTypeEnum.WIRE;
					
					case IfcTendonTypeEnum.BAR:
						return Ifc4.StructuralElementsDomain.IfcTendonTypeEnum.BAR;
					
					case IfcTendonTypeEnum.COATED:
						return Ifc4.StructuralElementsDomain.IfcTendonTypeEnum.COATED;
					
					case IfcTendonTypeEnum.USERDEFINED:
						return Ifc4.StructuralElementsDomain.IfcTendonTypeEnum.USERDEFINED;
					
					case IfcTendonTypeEnum.NOTDEFINED:
						return Ifc4.StructuralElementsDomain.IfcTendonTypeEnum.NOTDEFINED;
					
					
					default:
						throw new System.ArgumentOutOfRangeException();
				}
			} 
		}
		Ifc4.MeasureResource.IfcPositiveLengthMeasure? IIfcTendon.NominalDiameter 
		{ 
			get
			{
				return new Ifc4.MeasureResource.IfcPositiveLengthMeasure(NominalDiameter);
			} 
		}
		Ifc4.MeasureResource.IfcAreaMeasure? IIfcTendon.CrossSectionArea 
		{ 
			get
			{
				return new Ifc4.MeasureResource.IfcAreaMeasure(CrossSectionArea);
			} 
		}
		Ifc4.MeasureResource.IfcForceMeasure? IIfcTendon.TensionForce 
		{ 
			get
			{
				if (!TensionForce.HasValue) return null;
				return new Ifc4.MeasureResource.IfcForceMeasure(TensionForce.Value);
			} 
		}
		Ifc4.MeasureResource.IfcPressureMeasure? IIfcTendon.PreStress 
		{ 
			get
			{
				if (!PreStress.HasValue) return null;
				return new Ifc4.MeasureResource.IfcPressureMeasure(PreStress.Value);
			} 
		}
		Ifc4.MeasureResource.IfcNormalisedRatioMeasure? IIfcTendon.FrictionCoefficient 
		{ 
			get
			{
				if (!FrictionCoefficient.HasValue) return null;
				return new Ifc4.MeasureResource.IfcNormalisedRatioMeasure(FrictionCoefficient.Value);
			} 
		}
		Ifc4.MeasureResource.IfcPositiveLengthMeasure? IIfcTendon.AnchorageSlip 
		{ 
			get
			{
				if (!AnchorageSlip.HasValue) return null;
				return new Ifc4.MeasureResource.IfcPositiveLengthMeasure(AnchorageSlip.Value);
			} 
		}
		Ifc4.MeasureResource.IfcPositiveLengthMeasure? IIfcTendon.MinCurvatureRadius 
		{ 
			get
			{
				if (!MinCurvatureRadius.HasValue) return null;
				return new Ifc4.MeasureResource.IfcPositiveLengthMeasure(MinCurvatureRadius.Value);
			} 
		}

	//## Custom code
	//##
	}
}