// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;

// ReSharper disable once CheckNamespace
namespace Xbim.Ifc2x3.HVACDomain
{
	public partial class @IfcTubeBundleType : IIfcTubeBundleType
	{
		Xbim.Ifc4.HvacDomain.IfcTubeBundleTypeEnum IIfcTubeBundleType.PredefinedType 
		{ 
			get
			{
				switch (PredefinedType)
				{
					case Xbim.Ifc2x3.HVACDomain.IfcTubeBundleTypeEnum.FINNED:
						return Xbim.Ifc4.HvacDomain.IfcTubeBundleTypeEnum.FINNED;
					
					case Xbim.Ifc2x3.HVACDomain.IfcTubeBundleTypeEnum.USERDEFINED:
						return Xbim.Ifc4.HvacDomain.IfcTubeBundleTypeEnum.USERDEFINED;
					
					case Xbim.Ifc2x3.HVACDomain.IfcTubeBundleTypeEnum.NOTDEFINED:
						return Xbim.Ifc4.HvacDomain.IfcTubeBundleTypeEnum.NOTDEFINED;
					
					
					default:
						throw new System.ArgumentOutOfRangeException();
				}
			} 
		}
	}
}