// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;

// ReSharper disable once CheckNamespace
namespace Xbim.Ifc2x3.SharedBldgElements
{
	public partial class @IfcWindowLiningProperties : IIfcWindowLiningProperties
	{
		Ifc4.MeasureResource.IfcPositiveLengthMeasure? IIfcWindowLiningProperties.LiningDepth 
		{ 
			get
			{
				if (!LiningDepth.HasValue) return null;
				return new Ifc4.MeasureResource.IfcPositiveLengthMeasure(LiningDepth.Value);
			} 
			set
			{
				if (!value.HasValue)
				{
					LiningDepth =  null ;
					return;
				}
				LiningDepth = new MeasureResource.IfcPositiveLengthMeasure(value.Value);
				
			}
		}
		Ifc4.MeasureResource.IfcNonNegativeLengthMeasure? IIfcWindowLiningProperties.LiningThickness 
		{ 
			get
			{
				if (!LiningThickness.HasValue) return null;
				return new Ifc4.MeasureResource.IfcNonNegativeLengthMeasure(LiningThickness.Value);
			} 
			set
			{
				if (!value.HasValue)
				{
					LiningThickness =  null ;
					return;
				}
				LiningThickness = new MeasureResource.IfcPositiveLengthMeasure(value.Value);
				
			}
		}
		Ifc4.MeasureResource.IfcNonNegativeLengthMeasure? IIfcWindowLiningProperties.TransomThickness 
		{ 
			get
			{
				if (!TransomThickness.HasValue) return null;
				return new Ifc4.MeasureResource.IfcNonNegativeLengthMeasure(TransomThickness.Value);
			} 
			set
			{
				if (!value.HasValue)
				{
					TransomThickness =  null ;
					return;
				}
				TransomThickness = new MeasureResource.IfcPositiveLengthMeasure(value.Value);
				
			}
		}
		Ifc4.MeasureResource.IfcNonNegativeLengthMeasure? IIfcWindowLiningProperties.MullionThickness 
		{ 
			get
			{
				if (!MullionThickness.HasValue) return null;
				return new Ifc4.MeasureResource.IfcNonNegativeLengthMeasure(MullionThickness.Value);
			} 
			set
			{
				if (!value.HasValue)
				{
					MullionThickness =  null ;
					return;
				}
				MullionThickness = new MeasureResource.IfcPositiveLengthMeasure(value.Value);
				
			}
		}
		Ifc4.MeasureResource.IfcNormalisedRatioMeasure? IIfcWindowLiningProperties.FirstTransomOffset 
		{ 
			get
			{
				if (!FirstTransomOffset.HasValue) return null;
				return new Ifc4.MeasureResource.IfcNormalisedRatioMeasure(FirstTransomOffset.Value);
			} 
			set
			{
				if (!value.HasValue)
				{
					FirstTransomOffset =  null ;
					return;
				}
				FirstTransomOffset = new MeasureResource.IfcNormalisedRatioMeasure(value.Value);
				
			}
		}
		Ifc4.MeasureResource.IfcNormalisedRatioMeasure? IIfcWindowLiningProperties.SecondTransomOffset 
		{ 
			get
			{
				if (!SecondTransomOffset.HasValue) return null;
				return new Ifc4.MeasureResource.IfcNormalisedRatioMeasure(SecondTransomOffset.Value);
			} 
			set
			{
				if (!value.HasValue)
				{
					SecondTransomOffset =  null ;
					return;
				}
				SecondTransomOffset = new MeasureResource.IfcNormalisedRatioMeasure(value.Value);
				
			}
		}
		Ifc4.MeasureResource.IfcNormalisedRatioMeasure? IIfcWindowLiningProperties.FirstMullionOffset 
		{ 
			get
			{
				if (!FirstMullionOffset.HasValue) return null;
				return new Ifc4.MeasureResource.IfcNormalisedRatioMeasure(FirstMullionOffset.Value);
			} 
			set
			{
				if (!value.HasValue)
				{
					FirstMullionOffset =  null ;
					return;
				}
				FirstMullionOffset = new MeasureResource.IfcNormalisedRatioMeasure(value.Value);
				
			}
		}
		Ifc4.MeasureResource.IfcNormalisedRatioMeasure? IIfcWindowLiningProperties.SecondMullionOffset 
		{ 
			get
			{
				if (!SecondMullionOffset.HasValue) return null;
				return new Ifc4.MeasureResource.IfcNormalisedRatioMeasure(SecondMullionOffset.Value);
			} 
			set
			{
				if (!value.HasValue)
				{
					SecondMullionOffset =  null ;
					return;
				}
				SecondMullionOffset = new MeasureResource.IfcNormalisedRatioMeasure(value.Value);
				
			}
		}
		IIfcShapeAspect IIfcWindowLiningProperties.ShapeAspectStyle 
		{ 
			get
			{
				return ShapeAspectStyle;
			} 
			set
			{
				ShapeAspectStyle = value as RepresentationResource.IfcShapeAspect;
				
			}
		}
		Ifc4.MeasureResource.IfcLengthMeasure? IIfcWindowLiningProperties.LiningOffset 
		{ 
			get
			{
				//## Handle return of LiningOffset for which no match was found
                return null;
				//##
			} 
			set
			{
				//## Handle setting of LiningOffset for which no match was found
				//TODO: Handle setting of LiningOffset for which no match was found
				throw new System.NotImplementedException();
				//##
				
			}
		}
		Ifc4.MeasureResource.IfcLengthMeasure? IIfcWindowLiningProperties.LiningToPanelOffsetX 
		{ 
			get
			{
				//## Handle return of LiningToPanelOffsetX for which no match was found
                return null;
				//##
			} 
			set
			{
				//## Handle setting of LiningToPanelOffsetX for which no match was found
				//TODO: Handle setting of LiningToPanelOffsetX for which no match was found
				throw new System.NotImplementedException();
				//##
				
			}
		}
		Ifc4.MeasureResource.IfcLengthMeasure? IIfcWindowLiningProperties.LiningToPanelOffsetY 
		{ 
			get
			{
				//## Handle return of LiningToPanelOffsetY for which no match was found
                return null;
				//##
			} 
			set
			{
				//## Handle setting of LiningToPanelOffsetY for which no match was found
				//TODO: Handle setting of LiningToPanelOffsetY for which no match was found
				throw new System.NotImplementedException();
				//##
				
			}
		}
	//## Custom code
	//##
	}
}