// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Xbim.Common;

// ReSharper disable once CheckNamespace
namespace Xbim.IfcRail.GeometryResource
{
	public partial class @IfcReparametrisedCompositeCurveSegment : IIfcReparametrisedCompositeCurveSegment
	{

		[CrossSchemaAttribute(typeof(IIfcReparametrisedCompositeCurveSegment), 4)]
		Ifc4.MeasureResource.IfcParameterValue IIfcReparametrisedCompositeCurveSegment.ParamLength 
		{ 
			get
			{
				return new Ifc4.MeasureResource.IfcParameterValue(ParamLength);
			} 
			set
			{
				ParamLength = new MeasureResource.IfcParameterValue(value);
				
			}
		}
	//## Custom code
	//##
	}
}