// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool Xbim.CodeGeneration 
//  
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Xbim.Ifc4.Interfaces;
using System.Collections.Generic;
using System.Linq;
using Xbim.Common;

//## Custom using statements
//##

// ReSharper disable once CheckNamespace
namespace Xbim.Ifc4x3.ConstructionMgmtDomain
{
	public partial class @IfcConstructionResource : IIfcConstructionResource
	{

		[CrossSchemaAttribute(typeof(IIfcConstructionResource), 8)]
		IIfcResourceTime IIfcConstructionResource.Usage 
		{ 
			get
			{
				return Usage;
			} 
			set
			{
				Usage = value as DateTimeResource.IfcResourceTime;
				
			}
		}

		[CrossSchemaAttribute(typeof(IIfcConstructionResource), 9)]
		IItemSet<IIfcAppliedValue> IIfcConstructionResource.BaseCosts 
		{ 
			get
			{
			
				return new Common.Collections.ProxyItemSet<CostResource.IfcAppliedValue, IIfcAppliedValue>(BaseCosts);
			} 
		}

		[CrossSchemaAttribute(typeof(IIfcConstructionResource), 10)]
		IIfcPhysicalQuantity IIfcConstructionResource.BaseQuantity 
		{ 
			get
			{
				return BaseQuantity;
			} 
			set
			{
				BaseQuantity = value as QuantityResource.IfcPhysicalQuantity;
				
			}
		}
	//## Custom code
	//##
	}
}